import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;
import java.io.*;
import java.util.ArrayList;
import java.util.List;
import java.util.Arrays;
/**
 * JUnit test cases for the Database class
 * Testing focuses on file I/O operations and core business logic
 * relating to Accounts and Reservations
 * NOTE: this test class relies on the Account, Seat, and Reservation classes being available
 * due to the hardcoded file paths in Database.java, we must use the actual file names and
 * ensure they're cleaned up before and after every test run
 *
 * @author Shalini Murthula, Saanvi Verma
 * @version November 9, 2025
 */
public class DatabaseTest {

    private Database db;

    // file names must match the hardcoded names in Database.java
    private static final String ACCOUNT_FILE = "accounts.txt";
    private static final String SEATS_FILE = "seats.txt";
    private static final String RESERVATIONS_FILE = "reservations.txt";

    // sample account data
    private final String F_NAME = "Alice";
    private final String L_NAME = "Smith";
    private final int AGE = 30;
    private final String USERNAME = "asmith";
    private final String PASSWORD = "pass123";
    private final String EMAIL = "alice@test.com";
    private final String PHONE = "1234567890";

    // placeholder
    private String generatedID = null;

    // sample seat data
    private final String SEAT_ID_1 = "A1";
    private final String SEAT_AVAILABLE = SEAT_ID_1 + ",A,true,1,50.00";
    private final String SEAT_RESERVED = SEAT_ID_1 + ",A,false,1,50.00";

    // setup method to initialize the Database and ensure files are clean before each test
    @BeforeEach
    public void setUp() throws IOException {
        cleanUpFiles();

        // initialize the Database
        db = new Database();

        // ensure files are empty after initialization
        try (PrintWriter pw1 = new PrintWriter(ACCOUNT_FILE);
             PrintWriter pw2 = new PrintWriter(SEATS_FILE);
             PrintWriter pw3 = new PrintWriter(RESERVATIONS_FILE)) {

        }
    }

    // method to delete the files after each test
    @AfterEach
    public void tearDown() {
        cleanUpFiles();
    }

    // helper method to clean up the files
    private void cleanUpFiles() {
        new File(ACCOUNT_FILE).delete();
        new File(SEATS_FILE).delete();
        new File(RESERVATIONS_FILE).delete();
    }

    // helper method to retrieve the actual ID generated by createAccount,
    // since the ID logic is internal to the Account class
    private String getLatestAccountID() throws IOException {
        String lastLine = null;
        try (BufferedReader br = new BufferedReader(new FileReader(ACCOUNT_FILE))) {
            String line;
            while ((line = br.readLine()) != null) {
                if (!line.trim().isEmpty()) {
                    lastLine = line;
                }
            }
        }
        if (lastLine != null) {
            String[] parts = lastLine.split(",");
            // the ID is the last field (index 7) based on the deleteAccount logic
            return parts[7];
        }
        return null;
    }

    // -- ACCOUNT TESTS --

    @Test
    public void testCreateAccountSuccess() throws IOException {
        assertTrue(db.createAccount(F_NAME, L_NAME, AGE, USERNAME, PASSWORD, EMAIL, PHONE), "Account creation should succeed.");

        generatedID = getLatestAccountID();
        assertNotNull(generatedID, "Generated account ID should not be null after creation.");

        // verify the account exists and can be logged into
        assertTrue(db.loginIntoAccount(USERNAME, PASSWORD), "Login should succeed after creation.");
    }

    @Test
    public void testCreateAccountFailureDuplicateUsername() {
        // create the first account
        db.createAccount(F_NAME, L_NAME, AGE, USERNAME, PASSWORD, EMAIL, PHONE);

        // attempt to create a second account with the same username
        assertFalse(db.createAccount("Bob", "Jones", 25, USERNAME, "newpass", "bob@test.com", "9876543210"), "Duplicate username should fail creation.");

        // verify only one account exists in the file (by trying to log in with the second password)
        assertFalse(db.loginIntoAccount(USERNAME, "newpass"), "Login with duplicate account should fail.");
    }

    @Test
    public void testLoginIntoAccountSuccess() {
        db.createAccount(F_NAME, L_NAME, AGE, USERNAME, PASSWORD, EMAIL, PHONE);
        assertTrue(db.loginIntoAccount(USERNAME, PASSWORD), "Login should succeed with correct credentials.");
    }

    @Test
    public void testDeleteAccountSuccess() throws IOException {
        // create account
        db.createAccount(F_NAME, L_NAME, AGE, USERNAME, PASSWORD, EMAIL, PHONE);
        generatedID = getLatestAccountID();
        assertNotNull(generatedID, "Setup failed: Account ID not retrieved.");

        Account account = db.getAccount(generatedID, PASSWORD);
        assertNotNull(account, "Account should be retrievable before deletion.");

        // delete account
        assertTrue(db.deleteAccount(generatedID, USERNAME, PASSWORD), "Deletion should succeed with correct credentials.");

        // verify deletion by attempting to log in/retrieve
        assertFalse(db.loginIntoAccount(USERNAME, PASSWORD), "Login should fail after deletion.");
        assertNull(db.getAccount(generatedID, PASSWORD), "getAccount should return null after deletion.");
    }

    @Test
    public void testDeleteAccountFailureInvalidCredentials() throws IOException {
        db.createAccount(F_NAME, L_NAME, AGE, USERNAME, PASSWORD, EMAIL, PHONE);
        generatedID = getLatestAccountID();

        // attempt deletion with the wrong password
        assertFalse(db.deleteAccount(generatedID, USERNAME, "WRONG"), "Deletion should fail with incorrect password.");

        // verify the account is still there
        assertTrue(db.loginIntoAccount(USERNAME, PASSWORD), "Login should still succeed after failed deletion.");
    }

    @Test
    public void testGetAccountSuccess() throws IOException {
        db.createAccount(F_NAME, L_NAME, AGE, USERNAME, PASSWORD, EMAIL, PHONE);
        generatedID = getLatestAccountID();

        Account account = db.getAccount(generatedID, PASSWORD);

        assertNotNull(account, "getAccount should return the Account object.");
        assertEquals(USERNAME, account.getUserName(), "Retrieved account username must match.");
        assertEquals(generatedID, account.getID(), "Retrieved account ID must match.");
    }

    // -- SEAT METHODS --

    @Test
    public void testGetSeatSuccess() throws IOException {
        // write the seat data directly to the seats file
        try (FileWriter fw = new FileWriter(SEATS_FILE)) {
            fw.write(SEAT_AVAILABLE + "\n");
        }

        Seat seat = db.getSeat(SEAT_ID_1);

        assertNotNull(seat, "getSeat should retrieve the seat from file.");
        assertEquals(SEAT_ID_1, seat.getSeatID());
        assertTrue(seat.isAvailable(), "Seat should be available as it's set up.");
    }

    // -- RESERVATION TESTS --

    @Test
    public void testCreateReservationSuccess() throws IOException {
        // setup account
        db.createAccount(F_NAME, L_NAME, AGE, USERNAME, PASSWORD, EMAIL, PHONE);
        generatedID = getLatestAccountID();
        Account account = db.getAccount(generatedID, PASSWORD);

        String showID = "S101";
        List<String> seatIDs = Arrays.asList("A1", "A2");
        double price = 100.00;

        String reservationIDStr = db.createReservation(account, showID, seatIDs, "2025-12-01", "19:00", price);
        assertNotNull(reservationIDStr, "Reservation ID should be returned on success.");

        int reservationID = Integer.parseInt(reservationIDStr);
        Reservations res = db.getReservationByID(reservationID);

        assertNotNull(res, "Reservation should be retrievable by ID after creation.");
        assertEquals(generatedID, res.getUserID());
        assertEquals(seatIDs, res.getSeatIDs());
    }

    @Test
    public void testCancelReservationSuccess() throws IOException {
        // setup account and seat
        db.createAccount(F_NAME, L_NAME, AGE, USERNAME, PASSWORD, EMAIL, PHONE);
        generatedID = getLatestAccountID();
        Account account = db.getAccount(generatedID, PASSWORD);

        // write the seat data directly to the seats file
        try (FileWriter fw = new FileWriter(SEATS_FILE)) {
            fw.write(SEAT_RESERVED + "\n");
        }

        // create reservation
        String resIDStr = db.createReservation(account, "S101", Arrays.asList(SEAT_ID_1), "2025-12-01", "19:00", 50.00);
        int resID = Integer.parseInt(resIDStr);

        // cancel the reservation
        assertTrue(db.cancelReservation(resID), "Cancellation should succeed.");

        // reservation should be gone
        assertNull(db.getReservationByID(resID), "Reservation should be removed from file.");

        // seat availability should be updated
        Seat seat = db.getSeat(SEAT_ID_1);
        assertTrue(seat.isAvailable(), "The cancelled seat should be marked available (true) in the seats file.");
    }

    @Test
    public void testGetReservationByAccountSuccess() throws IOException {
        db.createAccount(F_NAME, L_NAME, AGE, USERNAME, PASSWORD, EMAIL, PHONE);
        generatedID = getLatestAccountID();
        Account account = db.getAccount(generatedID, PASSWORD);

        // create two reservations for this user
        String resID1Str = db.createReservation(account, "S101", Arrays.asList("A1"), "D1", "T1", 50.0);
        String resID2Str = db.createReservation(account, "S102", Arrays.asList("B2"), "D2", "T2", 60.0);

        int resID1 = Integer.parseInt(resID1Str);
        int resID2 = Integer.parseInt(resID2Str);

        // create one reservation for another user
        Account otherAccount = new Account("B", "X", 40, "bx", "p", "b@x.com", "9999999999");
        db.createAccount(otherAccount.getFirstName(), otherAccount.getLastName(), otherAccount.getAge(), otherAccount.getUserName(), otherAccount.getPassword(), otherAccount.getEmail(), otherAccount.getPhoneNumber());

        // retrieve reservations for the first user
        ArrayList<Reservations> userReservations = db.getReservationsByAccount(generatedID);

        assertEquals(2, userReservations.size(), "Should retrieve exactly two reservations for the account ID.");

        // check IDs
        List<Integer> expectedIDs = Arrays.asList(resID1, resID2);
        assertTrue(expectedIDs.contains(userReservations.get(0).getReservationID()));
        assertTrue(expectedIDs.contains(userReservations.get(1).getReservationID()));
    }
}
