import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;
import java.io.*;
import java.util.ArrayList;
import java.util.List;
import java.util.Arrays;
import java.util.concurrent.*;

/**
 * JUnit test cases for the Database class
 * Testing focuses on file I/O operations and core business logic
 * relating to Accounts and Reservations
 * NOTE: this test class relies on the Account, Seat, Reservation, and Concert classes
 * being available due to the hardcoded file paths in Database.java, we must use the
 * actual file names and ensure they're cleaned up before and after every test run
 *
 * @author Shalini Murthula (smurthul), Saanvi Verma (verma279), Kunj Arora (arora271)
 * @version November 9, 2025
 */
public class DatabaseTest {

    private Database db;

    // file names must match the hardcoded names in Database.java
    private static final String ACCOUNT_FILE = "accounts.txt";
    private static final String SEATS_FILE = "seats.txt";
    private static final String RESERVATIONS_FILE = "reservations.txt";
    private static final String CONCERT_FILE = "concert.txt";

    // sample account data
    private final String firstName = "Alice";
    private final String lastName = "Smith";
    private final int age = 30;
    private final String username = "asmith";
    private final String password = "pass123";
    private final String email = "alice@test.com";
    private final String phoneNumber = "1234567890";

    // placeholder
    private String generatedID = null;

    // sample seat data
    private final String seatId1 = "A1";
    private final String seatAvaliable = seatId1 + ",A,true,1,50.00";
    private final String seatReserved = seatId1 + ",A,false,1,50.00";

    String showID = "BillieEilishConcert"; // dummy show ID

    // setup method to initialize the Database and ensure files are clean before each test
    @BeforeEach
    public void setUp() throws IOException {
        cleanUpFiles();

        // initialize the Database
        db = new Database();

        // ensure files are empty after initialization
        try (PrintWriter pw1 = new PrintWriter(ACCOUNT_FILE);
             PrintWriter pw2 = new PrintWriter(SEATS_FILE);
             PrintWriter pw3 = new PrintWriter(RESERVATIONS_FILE)) {
        }
    }

    // method to delete the files after each test
    @AfterEach
    public void tearDown() {
        cleanUpFiles();
    }

    // helper method to clean up the files
    private void cleanUpFiles() {
        new File(ACCOUNT_FILE).delete();
        new File(SEATS_FILE).delete();
        new File(RESERVATIONS_FILE).delete();
        new File(CONCERT_FILE).delete();

        // clean up concert files
        new File("ConcertS101").delete();
        new File("ConcertS102").delete();
    }

    // helper method to retrieve the actual ID generated by createAccount,
    // since the ID logic is internal to the Account class
    private String getLatestAccountID() throws IOException {
        String lastLine = null;
        try (BufferedReader br = new BufferedReader(new FileReader(ACCOUNT_FILE))) {
            String line;
            while ((line = br.readLine()) != null) {
                if (!line.trim().isEmpty()) {
                    lastLine = line;
                }
            }
        }
        if (lastLine != null) {
            String[] parts = lastLine.split(",");
            // the ID is the last field (index 7) based on the deleteAccount logic
            return parts[7];
        }
        return null;
    }

    // -- ACCOUNT TESTS --

    @Test
    public void testCreateAccountSuccess() throws IOException {
        assertTrue(db.createAccount(firstName, lastName, age, username, password, email, phoneNumber),
                "Account creation should succeed.");

        generatedID = getLatestAccountID();
        assertNotNull(generatedID, "Generated account ID should not be null after creation.");

        // verify the account exists and can be logged into
        assertTrue(db.loginIntoAccount(username, password), "Login should succeed after creation.");
    }

    @Test
    public void testCreateAccountFailureDuplicateUsername() {
        // create the first account
        db.createAccount(firstName, lastName, age, username, password, email, phoneNumber);

        // attempt to create a second account with the same username
        assertFalse(db.createAccount("Bob", "Jones", 25, username, "newpass", "bob@test.com", "9876543210"),
                "Duplicate username should fail creation.");

        // verify only one account exists in the file (by trying to log in with the second password)
        assertFalse(db.loginIntoAccount(username, "newpass"), "Login with duplicate account should fail.");
    }

    @Test
    public void testLoginIntoAccountSuccess() {
        db.createAccount(firstName, lastName, age, username, password, email, phoneNumber);
        assertTrue(db.loginIntoAccount(username, password), "Login should succeed with correct credentials.");
    }

    @Test
    public void testDeleteAccountSuccess() throws IOException {
        // create account
        db.createAccount(firstName, lastName, age, username, password, email, phoneNumber);
        generatedID = getLatestAccountID();
        assertNotNull(generatedID, "Setup failed: Account ID not retrieved.");

        Account account = db.getAccount(generatedID, password);
        assertNotNull(account, "Account should be retrievable before deletion.");

        // delete account
        assertTrue(db.deleteAccount(generatedID, username, password),
                "Deletion should succeed with correct credentials.");

        // verify deletion by attempting to log in/retrieve
        assertFalse(db.loginIntoAccount(username, password), "Login should fail after deletion.");
        assertNull(db.getAccount(generatedID, password), "getAccount should return null after deletion.");
    }

    @Test
    public void testDeleteAccountFailureInvalidCredentials() throws IOException {
        db.createAccount(firstName, lastName, age, username, password, email, phoneNumber);
        generatedID = getLatestAccountID();

        // attempt deletion with the wrong password
        assertFalse(db.deleteAccount(generatedID, username, "WRONG"), "Deletion should fail with incorrect password.");

        // verify the account is still there
        assertTrue(db.loginIntoAccount(username, password), "Login should still succeed after failed deletion.");
    }

    @Test
    public void testGetAccountSuccess() throws IOException {
        db.createAccount(firstName, lastName, age, username, password, email, phoneNumber);
        generatedID = getLatestAccountID();

        Account account = db.getAccount(generatedID, password);

        assertNotNull(account, "getAccount should return the Account object.");
        assertEquals(username, account.getUserName(), "Retrieved account username must match.");
        assertEquals(generatedID, account.getID(), "Retrieved account ID must match.");
    }

    @Test
    public void testCreateAccountWithInvalidFields() {
        assertFalse(db.createAccount("", lastName, age, "userX", password, email, phoneNumber),
                "Empty first name should fail.");
        assertFalse(db.createAccount(firstName, "", age, "userX2", password, email, phoneNumber),
                "Empty last name should fail.");
        assertFalse(db.createAccount(firstName, lastName, -1, "userX3", password, email, phoneNumber),
                "Negative age should fail.");
        assertFalse(db.createAccount(firstName, lastName, age, "", password, email, phoneNumber),
                "Empty username should fail.");
    }

    @Test
    public void testLoginWithNonExistentUser() {
        assertFalse(db.loginIntoAccount("nonexistent", "nopass"), "Login should fail for non-existent user.");
    }

    // -- SEAT TESTS --

    @Test
    public void testGetSeatSuccess() throws IOException {
        String localShowID = "S101"; // use a specific, expected show ID
        String concertSeatFile = "Concert" + localShowID;

        // write the seat data to the concert file
        try (FileWriter fw = new FileWriter(concertSeatFile)) {
            fw.write("101\n");
            fw.write(seatAvaliable + "\n");
        }

        Seat seat = db.getSeat(localShowID, seatId1);

        assertNotNull(seat, "getSeat should retrieve the seat from file.");
        assertEquals(seatId1, seat.getSeatID());
        assertTrue(seat.isAvailable(), "Seat should be available as it's set up.");
    }

    @Test
    public void testGetNonExistentSeat() {
        Seat seat = db.getSeat("Z99", "S101");
        assertNull(seat, "Non-existent seat should return null.");
    }

    // -- RESERVATION TESTS --

    @Test
    public void testCreateReservationSuccess() throws IOException {
        // setup account
        db.createAccount(firstName, lastName, age, username, password, email, phoneNumber);
        generatedID = getLatestAccountID();
        Account account = db.getAccount(generatedID, password);

        String showID = "S101";
        List<String> seatIDs = Arrays.asList("A1", "A2");
        double price = 100.00;

        // create and populate necessary seat file
        String concertSeatFile = "Concert" + showID;
        try (FileWriter fw = new FileWriter(concertSeatFile)) {
            fw.write("101\n");
            fw.write("A1,A,true,1,50.00\n");
            fw.write("A2,A,true,1,50.00\n");
        }

        int reservationID = db.createReservation(account, showID, seatIDs, "2025-12-01", "19:00", price);
        assertTrue(reservationID > 0);

        Reservations res = db.getReservationByID(reservationID);

        assertNotNull(res, "Reservation should be retrievable by ID after creation.");
        assertEquals(generatedID, res.getUserID());
        assertEquals(seatIDs, res.getSeatIDs());
    }

    @Test
    public void testCancelReservationSuccess() throws IOException {
        // setup account and seat
        db.createAccount(firstName, lastName, age, username, password, email, phoneNumber);
        generatedID = getLatestAccountID();
        Account account = db.getAccount(generatedID, password);

        String showID = "S101";
        String SeatFile = "Concert" + showID;

        // write the seat data directly to the seats file
        try (FileWriter fw = new FileWriter(SeatFile)) {
            fw.write("101\n");
            String seatLine = seatId1 + ",A,false,1,50.00";
            fw.write(seatLine + "\n");
        }

        // create reservation
        int resID = db.createReservation(account, showID, Arrays.asList(seatId1), "2025-12-01", "19:00", 50.00);

        // cancel the reservation
        assertTrue(db.cancelReservation(resID), "Cancellation should succeed.");

        // reservation should be gone
        assertNull(db.getReservationByID(resID), "Reservation should be removed from file.");

        // seat availability should be updated
        Seat seat = db.getSeat(showID, seatId1);
        assertNotNull(seat, "Seat should be retrievable from the concert file after modification.");
        assertTrue(seat.isAvailable(), "The cancelled seat should be marked available (true) in the seats file.");
    }

    @Test
    public void testGetReservationByAccountSuccess() throws IOException {
        db.createAccount(firstName, lastName, age, username, password, email, phoneNumber);
        generatedID = getLatestAccountID();
        Account account = db.getAccount(generatedID, password);

        // ensure seat files exist for both reservations to succeed
        try (FileWriter fw1 = new FileWriter("ConcertS101");
             FileWriter fw2 = new FileWriter("ConcertS102")) {

            fw1.write("101\n");
            fw1.write("A1,A,true,1,50.00\n");

            fw2.write("102\n");
            fw2.write("B2,B,true,1,60.00\n");
        }

        // create two reservations for this user
        int resID1 = db.createReservation(account, "S101", Arrays.asList("A1"), "D1", "T1", 50.0);
        int resID2 = db.createReservation(account, "S102", Arrays.asList("B2"), "D2", "T2", 60.0);

        // create one reservation for another user
        Account otherAccount = new Account("B", "X", 40, "bx", "p", "b@x.com", "9999999999");
        db.createAccount(otherAccount.getFirstName(), otherAccount.getLastName(), otherAccount.getAge(),
                otherAccount.getUserName(), otherAccount.getPassword(), otherAccount.getEmail(),
                otherAccount.getPhoneNumber());

        // retrieve reservations for the first user
        ArrayList<Reservations> userReservations = db.getReservationsByAccount(generatedID);

        assertEquals(2, userReservations.size(), "Should retrieve exactly two reservations for the account ID.");

        // check IDs
        List<Integer> expectedIDs = Arrays.asList(resID1, resID2);
        assertTrue(expectedIDs.contains(userReservations.get(0).getReservationID()));
        assertTrue(expectedIDs.contains(userReservations.get(1).getReservationID()));
    }

    @Test
    public void testReserveNonExistentSeat() throws IOException {
        db.createAccount(firstName, lastName, age, username, password, email, phoneNumber);
        generatedID = getLatestAccountID();
        Account account = db.getAccount(generatedID, password);

        int resID = db.createReservation(account, "S101", Arrays.asList("Z99"), "D1", "T1", 50.0);
        assertEquals(-1, resID, "Reservation should fail for non-existent seat.");
    }

    @Test
    public void testCancelNonExistentReservation() {
        assertFalse(db.cancelReservation(9999), "Cancelling non-existent reservation should fail.");
    }

    // -- CONCERT TESTS --

    @Test
    public void testCreateAndReadConcert() throws IOException {
        // write sample concert to file
        try (FileWriter fw = new FileWriter(CONCERT_FILE)) {
            fw.write("S101,RockFest,2025-12-01,19:00,101\n");
        }

        // read concerts from file manually
        Concert concert = null;
        try (BufferedReader br = new BufferedReader(new FileReader(CONCERT_FILE))) {
            String line = br.readLine();
            if (line != null) {
                concert = new Concert(line);
            }
        }

        assertNotNull(concert, "Concert object should be created from file.");
        assertEquals("RockFest", concert.getName(), "Concert name should match.");
        assertEquals("2025-12-01", concert.getDate(), "Concert date should match.");
        assertEquals("19:00", concert.getTime(), "Concert time should match.");
        assertEquals(101, concert.getID(), "Concert ID should match.");
    }

    @Test
    public void testConcertFileMissing() throws IOException {
        // delete concert file to simulate missing file
        new File(CONCERT_FILE).delete();

        // attempt to read the file
        Concert concert = null;
        try (BufferedReader br = new BufferedReader(new FileReader(CONCERT_FILE))) {
            String line = br.readLine();
            if (line != null) {
                concert = new Concert(line);
            }
        } catch (IOException e) {
            concert = null;
        }

        assertNull(concert, "Concert should be null if concert.txt file is missing.");
    }

    @Test
    public void testMalformedConcertData() throws IOException {
        try (FileWriter fw = new FileWriter(CONCERT_FILE)) {
            fw.write("Malformed,Data,NoID\n");
        }
        Exception exception = null;
        try (BufferedReader br = new BufferedReader(new FileReader(CONCERT_FILE))) {
            String line = br.readLine();
            new Concert(line);
        } catch (Exception e) {
            exception = e;
        }
        assertNotNull(exception, "Malformed concert data should throw an exception.");
    }

    // -- CONCURRENCY/RACE CONDITION TESTS

    @Test
    public void testConcurrentAccountCreation() throws Exception {
        int threadCount = 5; // simulates 5 simultaneous account creations
        ExecutorService executor = Executors.newFixedThreadPool(threadCount);
        List<Future<Boolean>> results = new ArrayList<>();

        for (int i = 0; i < threadCount; i++) {
            final int idx = i;
            results.add(executor.submit(() -> db.createAccount("User" + idx, "Test", 25,
                    "user" + idx, "pass", "u" + idx + "@test.com", "1234567890")));
        }
        executor.shutdown();
        executor.awaitTermination(5, TimeUnit.SECONDS);

        for (Future<Boolean> f : results) {
            assertTrue(f.get(), "All concurrent account creations should succeed.");
        }

        // verify the correct number of accounts in the file
        try (BufferedReader br = new BufferedReader(new FileReader(ACCOUNT_FILE))) {
            int lines = 0;
            while (br.readLine() != null) {
                lines++;
            }
            assertEquals(threadCount, lines, "All accounts should be saved correctly in accounts.txt.");
        }
    }

    @Test
    public void testConcurrentReservationCreation() throws Exception {
        // prepare account
        db.createAccount(firstName, lastName, age, username, password, email, phoneNumber);
        generatedID = getLatestAccountID();
        Account account = db.getAccount(generatedID, password);

        String localShowID = "S101";
        String concertSeatFile = "Concert" + localShowID;

        // prepare seats file
        try (FileWriter fw = new FileWriter(concertSeatFile)) {
            fw.write("101\n");
            for (int i = 0; i < 5; i++) {
                fw.write("A" + i + ",A,true,1,50.00\n");
            }
        }

        int threadCount = 5;
        ExecutorService executor = Executors.newFixedThreadPool(threadCount);
        List<Future<Integer>> results = new ArrayList<>();

        for (int i = 0; i < threadCount; i++) {
            final int seatNum = i;
            results.add(executor.submit(() -> db.createReservation(account, "S101",
                    Arrays.asList("A" + seatNum), "2025-12-01", "19:00", 50.0)));
        }
        executor.shutdown();
        executor.awaitTermination(5, TimeUnit.SECONDS);

        for (Future<Integer> f : results) {
            int resID = f.get();
            assertTrue(resID > 0, "Each concurrent reservation should succeed.");
        }

        // verify all reservations exist
        ArrayList<Reservations> reservations = db.getReservationsByAccount(generatedID);
        assertEquals(threadCount, reservations.size(), "All reservations should be recorded correctly.");
    }

    @Test
    public void testConcurrentReservationSameSeat() throws Exception {
        db.createAccount(firstName, lastName, age, username, password, email, phoneNumber);
        generatedID = getLatestAccountID();
        Account account = db.getAccount(generatedID, password);

        String localShowID = "S101";
        String concertSeatFile = "Concert" + localShowID;

        try (FileWriter fw = new FileWriter(concertSeatFile)) {
            fw.write("101\n");
            fw.write("A1,A,true,1,50.00\n");
        }

        int threadCount = 2;
        ExecutorService executor = Executors.newFixedThreadPool(threadCount);
        List<Future<Integer>> results = new ArrayList<>();
        for (int i = 0; i < threadCount; i++) {
            results.add(executor.submit(() -> db.createReservation(account, "S101",
                    Arrays.asList("A1"), "2025-12-01", "19:00", 50.0)));
        }
        executor.shutdown();
        executor.awaitTermination(5, TimeUnit.SECONDS);

        int successfulReservations = 0;
        for (Future<Integer> f : results) {
            if (f.get() > 0) {
                successfulReservations++;
            }
        }
        assertEquals(1, successfulReservations, "Only one reservation should succeed for the same seat.");
    }

    // -- MALFORMED FILE TESTS --

    @Test
    public void testMalformedAccountFile() throws IOException {
        try (FileWriter fw = new FileWriter(ACCOUNT_FILE)) {
            // missing ID field
            fw.write("Alice,Smith,30,asmith,pass123,alice@test.com,1234567890\n");
            // empty line
            fw.write("\n");
            // correct
            fw.write("Bob,Jones,25,bjones,pass,bob@test.com,9876543210,ID123\n");
        }

        // only the correct account should be retrievable
        Account account = db.getAccount("ID123", "pass");
        assertNotNull(account, "Valid account line should still be retrievable.");

        // malformed line should not create an account
        Account invalidAccount = db.getAccount("", "pass");
        assertNotNull(invalidAccount, "Malformed line without ID should not create an account.");
    }

    @Test
    public void testMalformedSeatsFile() throws IOException {
        // define concert file name
        String localShowID = "S101";
        String concertSeatFile = "Concert" + localShowID;

        try (FileWriter fw = new FileWriter(concertSeatFile)) {
            fw.write("101\n");
            // missing price is invalid
            fw.write("A1,A,true,1\n");
            // availability not boolean
            fw.write("B2,B,notBool,2,60.0\n");
            // correct seat is valid
            fw.write("C3,C,true,3,70.0\n");
        }

        Seat validSeat = db.getSeat(localShowID, "C3");
        assertNotNull(validSeat, "Correct seat line should be retrievable.");

        // malformed seats should return null
        assertNull(db.getSeat(showID, "A1"), "Seat missing price should return null.");
        assertNull(db.getSeat(showID, "B2"), "Seat with invalid availability should return null.");
    }

    @Test
    public void testMalformedReservationsFile() throws IOException {
        try (FileWriter fw = new FileWriter(RESERVATIONS_FILE)) {
            // missing seat list
            fw.write("X,ID1,,2025-12-01,19:00,100.0\n");
            // negative price
            fw.write("2,ID2,A1,A2,2025-12-01,19:00,-50.0\n");
            // correct reservation
            fw.write("3,ID3,A3,2025-12-02,20:00,60.0\n");
        }

        // only the valid reservation should be retrievable
        Reservations validRes = db.getReservationByID(3);
        assertNotNull(validRes, "Valid reservation line should be retrievable.");

        // malformed reservations should return null
        assertNull(db.getReservationByID(99999), "Reservation with missing seat list should return null.");
    }

    @Test
    public void testMalformedConcertFile() throws IOException {
        try (FileWriter fw = new FileWriter(CONCERT_FILE)) {
            // missing time and ID
            fw.write("S101,RockFest,2025-12-01\n");
            // empty line
            fw.write("\n");
            // correct line
            fw.write("S102,PopFest,2025-12-02,20:00,102\n");
        }

        Concert validConcert = null;
        try (BufferedReader br = new BufferedReader(new FileReader(CONCERT_FILE))) {
            String line;
            while ((line = br.readLine()) != null) {
                try {
                    Concert c = new Concert(line);
                    if (c.getID() == 102) validConcert = c;
                } catch (Exception e) {
                    // ignore malformed lines
                    e.printStackTrace();
                }
            }
        }
        assertNotNull(validConcert, "Valid concert line should be retrievable.");
    }
}
